preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  com.android.application:
    alias: android-application
    version: 8.2.0
  com.android.library:
    alias: android-library
    version-ref: com.android.application
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: 1.9.21

libraries:
  com.highcapable.betterandroid:
    ui-component:
      version: 1.0.3
    ui-extension:
      version: 1.0.1
    system-extension:
      version: 1.0.0
  androidx.core:
    core:
      version: 1.12.0
    core-ktx:
      version-ref: <this>::core
  androidx.appcompat:
    appcompat:
      version: 1.6.1
  com.google.android.material:
    material:
      version: 1.10.0
  androidx.constraintlayout:
    constraintlayout:
      version: 2.1.4
  junit:
    junit:
      version: 4.13.2
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1